var yse1=document.getElementById("div_box-right-6-div-1");
	 	var yse2=document.getElementById("div_box-right-6-div-2");	
	 	var yse3=document.getElementById("div_box-right-6-div-3");	
	 	var yse4=document.getElementById("div_box-right-6-div-4");	
	 	var yse5=document.getElementById("div_box-right-6-div-5");	
	 	var yse6=document.getElementById("div_box-right-6-div-6");	
	 	var yse7=document.getElementById("div_box-right-6-div-7");	
	 	var yse8=document.getElementById("div_box-right-6-div-8");	
	 	var wrap    = document.getElementsByClassName("wrap")[0];
        var smallImgBox = wrap.getElementsByClassName("imgBox")[0];//div1
        var smallImg = smallImgBox.getElementsByTagName("img")[0];//图片1
        var bigImgBox = wrap.getElementsByClassName("imgBox")[1];//div2
        var bigImg = bigImgBox.getElementsByTagName("img")[0];//图片2
        yse1.onclick=function(){
        	yse1.style.border="2px solid #ff0036";
        	yse2.style.border="0.2px solid #e5e4e4";
        	yse3.style.border="0.2px solid #e5e4e4";
        	yse4.style.border="0.2px solid #e5e4e4";
        	yse5.style.border="0.2px solid #e5e4e4";
        	yse6.style.border="0.2px solid #e5e4e4";
        	yse7.style.border="0.2px solid #e5e4e4";
        	yse8.style.border="0.2px solid #e5e4e4";
        	smallImg.src="lj_images/yanse1.jpg";
        	bigImg.src="lj_images/yanse1.jpg";
        }
          yse2.onclick=function(){
        	yse2.style.border="2px solid #ff0036";
        	yse1.style.border="0.2px solid #e5e4e4";
        	yse3.style.border="0.2px solid #e5e4e4";
        	yse4.style.border="0.2px solid #e5e4e4";
        	yse5.style.border="0.2px solid #e5e4e4";
        	yse6.style.border="0.2px solid #e5e4e4";
        	yse7.style.border="0.2px solid #e5e4e4";
        	yse8.style.border="0.2px solid #e5e4e4";
        	smallImg.src="lj_images/yanse2.jpg";
        	bigImg.src="lj_images/yanse2.jpg";
        }
          yse3.onclick=function(){
        	yse3.style.border="2px solid #ff0036";
        	yse1.style.border="0.2px solid #e5e4e4";
        	yse2.style.border="0.2px solid #e5e4e4";
        	yse4.style.border="0.2px solid #e5e4e4";
        	yse5.style.border="0.2px solid #e5e4e4";
        	yse6.style.border="0.2px solid #e5e4e4";
        	yse7.style.border="0.2px solid #e5e4e4";
        	yse8.style.border="0.2px solid #e5e4e4";
        	smallImg.src="lj_images/yanse3.jpg";
        	bigImg.src="lj_images/yanse3.jpg";
        }
            yse4.onclick=function(){
        	yse4.style.border="2px solid #ff0036";
        	yse1.style.border="0.2px solid #e5e4e4";
        	yse2.style.border="0.2px solid #e5e4e4";
        	yse3.style.border="0.2px solid #e5e4e4";
        	yse5.style.border="0.2px solid #e5e4e4";
        	yse6.style.border="0.2px solid #e5e4e4";
        	yse7.style.border="0.2px solid #e5e4e4";
        	yse8.style.border="0.2px solid #e5e4e4";
        	smallImg.src="lj_images/yanse4.jpg";
        	bigImg.src="lj_images/yanse4.jpg";
        }
            yse5.onclick=function(){
        	yse5.style.border="2px solid #ff0036";
        	yse1.style.border="0.2px solid #e5e4e4";
        	yse2.style.border="0.2px solid #e5e4e4";
        	yse3.style.border="0.2px solid #e5e4e4";
        	yse4.style.border="0.2px solid #e5e4e4";
        	yse6.style.border="0.2px solid #e5e4e4";
        	yse7.style.border="0.2px solid #e5e4e4";
        	yse8.style.border="0.2px solid #e5e4e4";
        	smallImg.src="lj_images/yanse5.jpg";
        	bigImg.src="lj_images/yanse5.jpg";
        }
            yse6.onclick=function(){
        	yse6.style.border="2px solid #ff0036";
        	yse1.style.border="0.2px solid #e5e4e4";
        	yse2.style.border="0.2px solid #e5e4e4";
        	yse3.style.border="0.2px solid #e5e4e4";
        	yse4.style.border="0.2px solid #e5e4e4";
        	yse5.style.border="0.2px solid #e5e4e4";
        	yse7.style.border="0.2px solid #e5e4e4";
        	yse8.style.border="0.2px solid #e5e4e4";
        	smallImg.src="lj_images/yanse6.jpg";
        	bigImg.src="lj_images/yanse6.jpg";
        }
            yse7.onclick=function(){
        	yse7.style.border="2px solid #ff0036";
        	yse1.style.border="0.2px solid #e5e4e4";
        	yse2.style.border="0.2px solid #e5e4e4";
        	yse3.style.border="0.2px solid #e5e4e4";
        	yse4.style.border="0.2px solid #e5e4e4";
        	yse5.style.border="0.2px solid #e5e4e4";
        	yse6.style.border="0.2px solid #e5e4e4";
        	yse8.style.border="0.2px solid #e5e4e4";
        	smallImg.src="lj_images/yanse7.jpg";
        	bigImg.src="lj_images/yanse7.jpg";
        }
            yse8.onclick=function(){
        	yse8.style.border="2px solid #ff0036";
        	yse1.style.border="0.2px solid #e5e4e4";
        	yse2.style.border="0.2px solid #e5e4e4";
        	yse3.style.border="0.2px solid #e5e4e4";
        	yse4.style.border="0.2px solid #e5e4e4";
        	yse5.style.border="0.2px solid #e5e4e4";
        	yse6.style.border="0.2px solid #e5e4e4";
        	yse7.style.border="0.2px solid #e5e4e4";
        	smallImg.src="lj_images/yanse8.jpg";
        	bigImg.src="lj_images/yanse8.jpg";
        }